services:

  db:
    container_name: task_manager_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    volumes:
      - taskman_db:/var/lib/postgresql/data
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  web:
    container_name: task_manager_web
    image: realdmkael/task_manager:latest
    env_file:
      - .env
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}
    ports:
      - "8000:8000"
    command: bash -c "python manage.py migrate && make gunicorn"

volumes:
  taskman_db: