version: "2"
checks:
  similar-code:
    enabled: false
exclude_patterns:
  - "**/manage.py"
  - "**/asgi.py"
  - "**/wsgi.py"
  - "**/settings.py"
  - "**/static/"
  - "**/tests/"
  - "**/migrations/"