version: '3.9'
services:

  task_manager:
    container_name: task_manager_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    volumes:
      - taskman_db:/var/lib/postgresql/data
    restart: on-failure

volumes:
  taskman_db: