# Generated by Django 5.0.6 on 2024-06-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0003_task_labels_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(related_name='tasks', to='labels.label'),
        ),
    ]
